CREATE TABLE IF NOT EXISTS public."Pacientes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Telefono" text,
    "Email" text,
    "Direccion" text,
    "Edad" integer,
    "Ocupacion" text,
    "Notas" text,
    "FechaRegistro" timestamp with time zone NOT NULL,
    "EstaActivo" boolean NOT NULL,
    CONSTRAINT "PK_Pacientes_public" PRIMARY KEY ("Id")
);

CREATE SCHEMA IF NOT EXISTS public_test;

CREATE TABLE IF NOT EXISTS public_test."Pacientes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Telefono" text,
    "Email" text,
    "Direccion" text,
    "Edad" integer,
    "Ocupacion" text,
    "Notas" text,
    "FechaRegistro" timestamp with time zone NOT NULL,
    "EstaActivo" boolean NOT NULL,
    CONSTRAINT "PK_Pacientes_test" PRIMARY KEY ("Id")
);
