// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpticBackend.Data;

#nullable disable

namespace OpticBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260411010623_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OpticBackend.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreEsquema")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("OpticBackend.Models.ConfiguracionSistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ColorAcento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color_acento");

                    b.Property<string>("ColorPrimario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color_primario");

                    b.Property<string>("ColorSecundario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color_secundario");

                    b.Property<string>("ColorTextoBase")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color_texto_base");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("EmailContacto")
                        .HasColumnType("text")
                        .HasColumnName("email_contacto");

                    b.Property<string>("Eslogan")
                        .HasColumnType("text")
                        .HasColumnName("eslogan");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("NombreOptica")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_optica");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_actualizacion");

                    b.HasKey("Id");

                    b.ToTable("configuracion_sistema");
                });

            modelBuilder.Entity("OpticBackend.Models.Consultation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("CostoServicio")
                        .HasColumnType("numeric")
                        .HasColumnName("costo_servicio");

                    b.Property<string>("DetallesClinicos")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalles_clinicos");

                    b.Property<string>("EstadoFinanciero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_financiero");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<string>("MotivoConsulta")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("motivo_consulta");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<string>("TipoConsulta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_consulta");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("text")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("consultas");
                });

            modelBuilder.Entity("OpticBackend.Models.Graduation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConsultaId")
                        .HasColumnType("uuid")
                        .HasColumnName("consulta_id");

                    b.Property<string>("DetallesMontaje")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalles_montaje");

                    b.Property<decimal?>("OdAdicion")
                        .HasColumnType("numeric")
                        .HasColumnName("od_adicion");

                    b.Property<decimal?>("OdCilindro")
                        .HasColumnType("numeric")
                        .HasColumnName("od_cilindro");

                    b.Property<int?>("OdEje")
                        .HasColumnType("integer")
                        .HasColumnName("od_eje");

                    b.Property<decimal?>("OdEsfera")
                        .HasColumnType("numeric")
                        .HasColumnName("od_esfera");

                    b.Property<decimal?>("OiAdicion")
                        .HasColumnType("numeric")
                        .HasColumnName("oi_adicion");

                    b.Property<decimal?>("OiCilindro")
                        .HasColumnType("numeric")
                        .HasColumnName("oi_cilindro");

                    b.Property<int?>("OiEje")
                        .HasColumnType("integer")
                        .HasColumnName("oi_eje");

                    b.Property<decimal?>("OiEsfera")
                        .HasColumnType("numeric")
                        .HasColumnName("oi_esfera");

                    b.Property<string>("TipoGraduacion")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_graduacion");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.ToTable("graduaciones");
                });

            modelBuilder.Entity("OpticBackend.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApellidoMaterno")
                        .HasColumnType("text")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("ApellidoPaterno")
                        .HasColumnType("text")
                        .HasColumnName("apellido_paterno");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<string>("Ocupacion")
                        .HasColumnType("text")
                        .HasColumnName("ocupacion");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.ToTable("pacientes");
                });

            modelBuilder.Entity("OpticBackend.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("metodo_pago");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric")
                        .HasColumnName("monto");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("text")
                        .HasColumnName("usuario_id");

                    b.Property<Guid?>("VentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("venta_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VentaId");

                    b.ToTable("abonos");
                });

            modelBuilder.Entity("OpticBackend.Models.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ConsultaId")
                        .HasColumnType("uuid")
                        .HasColumnName("consulta_id");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("FolioFisico")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("folio_fisico");

                    b.Property<string>("MotivoCancelacion")
                        .HasColumnType("text")
                        .HasColumnName("motivo_cancelacion");

                    b.Property<string>("ObservacionesGenerales")
                        .HasColumnType("text")
                        .HasColumnName("observaciones_generales");

                    b.Property<decimal?>("SaldoPendiente")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo_pendiente");

                    b.Property<decimal?>("TotalVenta")
                        .HasColumnType("numeric")
                        .HasColumnName("total_venta");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("text")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ventas");
                });

            modelBuilder.Entity("OpticBackend.Models.SaleDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AlturaOblea")
                        .HasColumnType("numeric")
                        .HasColumnName("altura_oblea");

                    b.Property<Guid?>("CatalogoId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalogo_id");

                    b.Property<string>("DescripcionManual")
                        .HasColumnType("text")
                        .HasColumnName("descripcion_manual");

                    b.Property<decimal?>("DpOd")
                        .HasColumnType("numeric")
                        .HasColumnName("dp_od");

                    b.Property<decimal?>("DpOi")
                        .HasColumnType("numeric")
                        .HasColumnName("dp_oi");

                    b.Property<Guid?>("GraduacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("graduacion_id");

                    b.Property<Guid?>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<decimal?>("PrecioAplicado")
                        .HasColumnType("numeric")
                        .HasColumnName("precio_aplicado");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("venta_id");

                    b.HasKey("Id");

                    b.HasIndex("GraduacionId");

                    b.HasIndex("PacienteId");

                    b.HasIndex("VentaId");

                    b.ToTable("detalle_ventas");
                });

            modelBuilder.Entity("OpticBackend.Models.SalesCommission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<decimal>("MontoComision")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_comision");

                    b.Property<decimal>("PuntosVenta")
                        .HasColumnType("numeric")
                        .HasColumnName("puntos_venta");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid")
                        .HasColumnName("venta_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VentaId");

                    b.ToTable("comisiones_ventas");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OpticBackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OpticBackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpticBackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OpticBackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpticBackend.Models.Consultation", b =>
                {
                    b.HasOne("OpticBackend.Models.Patient", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpticBackend.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Paciente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OpticBackend.Models.Graduation", b =>
                {
                    b.HasOne("OpticBackend.Models.Consultation", "Consulta")
                        .WithMany("Graduaciones")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("OpticBackend.Models.Payment", b =>
                {
                    b.HasOne("OpticBackend.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.HasOne("OpticBackend.Models.Sale", "Venta")
                        .WithMany("Abonos")
                        .HasForeignKey("VentaId");

                    b.Navigation("Usuario");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("OpticBackend.Models.Sale", b =>
                {
                    b.HasOne("OpticBackend.Models.Consultation", "Consulta")
                        .WithMany()
                        .HasForeignKey("ConsultaId");

                    b.HasOne("OpticBackend.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Consulta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OpticBackend.Models.SaleDetail", b =>
                {
                    b.HasOne("OpticBackend.Models.Graduation", "Graduacion")
                        .WithMany()
                        .HasForeignKey("GraduacionId");

                    b.HasOne("OpticBackend.Models.Patient", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId");

                    b.HasOne("OpticBackend.Models.Sale", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Graduacion");

                    b.Navigation("Paciente");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("OpticBackend.Models.SalesCommission", b =>
                {
                    b.HasOne("OpticBackend.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpticBackend.Models.Sale", "Venta")
                        .WithMany("Comisiones")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("OpticBackend.Models.Consultation", b =>
                {
                    b.Navigation("Graduaciones");
                });

            modelBuilder.Entity("OpticBackend.Models.Sale", b =>
                {
                    b.Navigation("Abonos");

                    b.Navigation("Comisiones");

                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
