START TRANSACTION;
ALTER TABLE "AspNetUsers" ADD "NombreEsquema" text;

CREATE TABLE configuracion_sistema (
    id uuid NOT NULL,
    nombre_optica text NOT NULL,
    eslogan text,
    logo_url text,
    color_primario text NOT NULL,
    color_secundario text NOT NULL,
    color_acento text NOT NULL,
    color_texto_base text NOT NULL,
    direccion text,
    telefono text,
    email_contacto text,
    ultima_actualizacion timestamp with time zone NOT NULL,
    CONSTRAINT "PK_configuracion_sistema" PRIMARY KEY (id)
);

CREATE TABLE "Pacientes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Telefono" text,
    "Email" text,
    "Direccion" text,
    "Edad" integer,
    "Ocupacion" text,
    "Notas" text,
    "FechaRegistro" timestamp with time zone NOT NULL,
    "EstaActivo" boolean NOT NULL,
    CONSTRAINT "PK_Pacientes" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260201002339_AddPatientsTable', '9.0.0');

COMMIT;

